---
driver:
  name: vagrant
  vm_hostname: vagrantvm
  network:
    - ["private_network", {ip: "192.168.56.90"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: /home/student/cm/ansible/day-1/sbeliakou-centos-7.3-x86_64-minimal.box

suites:
  - name: default
    run_list:
      - recipe[task4_nginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
